  import Head from 'next/head'
  import {BsFillMoonStarsFill} from 'react-icons/bs';
  import {AiFillGithub,AiFillLinkedin} from 'react-icons/ai';
  import Image from 'next/image';
  import deved from "../public/dev-ed-wave.png"
  import code from "../public/code.png";
  import design from "../public/design.png";
  import consulting from "../public/consulting.png";
  import web1 from "../public/web1.png";
  import web2 from "../public/web2.png";
  import web3 from "../public/web3.png";
  import web4 from "../public/web4.png";
  import web5 from "../public/web5.png";
  import web6 from "../public/web6.png";
  import { useState } from "react";

  export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Davit</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='bg-white px-10 dark:bg-gray-900 '>
          <section className='min-h-screen'>

       {/* navigation */}
            {/* <nav className='py-10 mb-12 flex
            justify-between'>
              <h1 className='text-xl font-burtons dark:text-white'>Davit AI</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill 
                  onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer text-2xl color-b'/>
                  </li>
                <li>
                  <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
                  </li>
              </ul>
            </nav> */}

        {/* display page */}
          <div className='text-center p-5 py-2'>
            <h2 className='text-4xl py-2 text-teal-600 font-medium dark:text-teal-400'>Davit Khanal</h2>
            <h3 className='text-2xl py-2 dark:text-white'>Gamer | Support Engineer</h3>
            <p className='text-md py-5 leading-4 text-gray-700 dark:text-white'>Select * from gamer where name='davit';</p>
          </div>

          {/* button */}
          <div className='text-3xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin className='text-blue-600 dark:text-blue'/>
            <AiFillGithub className='text-gray-900 dark:text-white'/>
          </div>

            {/* image */}
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden'>
          <Image src={deved} fill objectFit="cover"/>
          </div>
          </section>

          {/* second page */}
          {/* career */}
          {/* <section>
          <div>
            <h3 className="text-3xl py-1 ">Career</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a IT enthuaist and gaming passion has idealize me to involve in 
              <span className="text-teal-500"> IT industry. </span>
            </p>
          </div>
          <div className="lg:flex gap-12">

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
               Intern
              </h3>
              <p className="py-2">
              INTERNSHIP IN NEPAL OLYMPIC MUSEUM
              </p>
              <h4 className="py-4 text-teal-600">2021</h4>
              <p className="text-gray-800 py-1">Data collection and database management for nepali sports personnel and officials</p>
              
            </div>

          </div>
        </section> */}
        {/* career end */}

        </main>
      </div>
    )
  }
